services:
  mps-static-nginx:
    image: nginx:latest
    container_name: mps-static-nginx
    hostname: mps-static-nginx
    restart: unless-stopped
    volumes:
      - ./mps/mps_site/static:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mps-static-nginx.entrypoints=web"
      - "traefik.http.routers.mps-static-nginx.rule=Host(`cdn.dcumps.ie`)"

networks:
  default:
    external:
      name: $DEFAULT_NETWORK